baseURL: "https://sunpodder.github.io/"
title: "Sun Podder"
paginate: 5
theme: papermod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: development # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Sun Podder's Portfolio"
  description: "Welcome to my portfolio"
  keywords: ["Sun Podder", "Sun Podder Portfolio", "SunPodder", "Sun", "Sunlight", "Sunlight Portfolio"]
  author: ["Sun"] # multiple authors
  images: ["/image/0.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: true
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/image/fav.ico"
    favicon16x16: "/image/16x16.png"
    favicon32x32: "/image/32x32.png"
    apple_touch_icon: "/image/32x32.png"
    safari_pinned_tab: "/image/0.png"

  label:
    text: "Sun Podder"
    icon: ""
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Sun Podder"
    subtitle: "Software Engineer"
    imageUrl: "/image/0.png"
    imageWidth: 128
    imageHeight: 128
    imageTitle: "Sun Podder"
    buttons:
      - name: Projects
        url: projects
      - name: Contact
        url: contact

  socialIcons:
    - name: github
      url: "https://github.com/SunPodder"
    - name: facebook
      url: "https://facebook.com/sun.podder.09"
    - name: linkedin
      url: "https://www.linkedin.com/in/sun-podder-610a63211"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 30
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
